language: node_js
node_js:
 - '12'
 - '10'
 - '8'
 - '6'

cache:
  directories:
    - node_modules

script:
  - yarn test -- --maxWorkers=4
  - yarn e2e -- --maxWorkers=4

after_success:
  - if [[ $(node --version) == "v12."* ]]; then yarn coverage; fi

stages:
  - test
  - publish documentation
  - deploy

jobs:
  include:
    - stage: test
      env: STEP=FORMAT_LINT
      script:
        - yarn format:check
        - yarn lint:check
    - stage: test
      env: STEP=EXAMPLES_ROLLUP_LEGACY
      script:
        - yarn build
        - cd example ;
          bash run.sh ;
          cd ..
        - yarn prebuild
        - yarn build:publish-cjs
        - yarn build:publish-esm
        - yarn webbuild
        - yarn test:rollup-esm
        - yarn test:rollup-iife
        - nvm install 0.12 ;
          node test/legacy/main.js
    - stage: test
      env: STEP=HEAD
      script:
        - rm -r node_modules/
        - rm package-lock.json
        - yarn
        - yarn test -- --maxWorkers=4
        - yarn e2e -- --maxWorkers=4
    - stage: publish documentation
      if: branch = master AND type = push
      script:
        - yarn prebuild
        - yarn build:publish-types
        - yarn docs
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        target-branch: gh-pages
        local-dir: docs
        on:
          branch: master
    - stage: deploy
      if: tag =~ ^v\d+\.
      script:
        - yarn prebuild
        - yarn build:publish-types
        - yarn build:publish-cjs
        - yarn build:publish-esm
        - yarn webbuild
      deploy:
        provider: npm
        email: npm@dubien.org
        skip_cleanup: true
        api_key:
          secure: pz02NsBWp2+V7L5ScpFig53wF7PbjROaiAXaPzaegyFMc6aPVVWdvh+wMMwbJPTd/zXY3CL0ktRyWJPLtv5ZGFWyIny6artteZ01ZHTDOy/aZVfvvWCAS3cyrwSWc9WTbOtl7O+yow2AEF6mXzUrfqAJeBgg1vkkP2ig5FaBqgY2aaQmGgvkBxImxwPwj/sKxYmCO4hHKKzXewHQkmP9uwVWs/z6e8EVufZYuBtGqB8OOfWTZuhW4Re9oiwTtp8HYCuiWwQI/Pe7G81rqktMJTqXymo041caucSs27Nko9b37RzPAeN4mgZmRbB2qoJJtjasMk5KJq76CPKAsVNwrDLaS6MzghcncHH50uOP/lzfr/YWGmUKD+PnTi5iOJ+OpY4AXgR/phrYsCkmGMrrQqjlA9e+HONoaEElJ9YnxcN36tb2wVNd+FwQ1dw+AlcSyVmIGZkD9pDNh+BTZ12SdtEu5qHuUotetIke3iOXjjOGbtr0ckCgWHtxFlcZMQEFVO9pTyz+f4mdgbMD9DSL7JD0Ns6pTtbGqBqVJmzA4IDVaD6xAedoMDte5QO+ltbM+vKlPIGIocQ6D+K+Z2l4oeiL5f54Lx28wyld0i5foGZGic2hh6ni6ie86/sLzAVBRHtfaiIrzqPztUBzbW+6/tTZI28zqFHLE7EobA7yB/0=
        on:
          tags: true
      repo: dubzzz/fast-check
